### ISSUE TITLE
博文《模块联邦浅析》内容和项目的配置不一致，导致实际运行时预期效果没有出现

### ISSUE THREAD

**Issue by PointerToNextPole** [AshesOfHistory/vue3-cli-module-federation-demo#1]
按照 博文 [模块联邦浅析](https://www.zoo.team/article/webpack-modular) 中的步骤一步步执行，运行项目后，发现没有出现博文中预期的效果。开始排查问题，并找到问题所在：

按博文中所说：
> 首先克隆本项目代码地址后，分别在 app-exposes 与 app-general 项目下执行 npm i 安装依赖，然后分别执行 npm run serve 运行代码。 此时能够看到本地起了两个服务，端口号分别为 8083 与 8081，其中 app-exposes 为 8083，app-general 为 8081。

项目运行后，发现 app-exposes 始终运行在 8082 端口下，而不是 博文中说的 8083（应该是端口不对，导致 ModuleFederationPlugin 的配置没有生效）。`vue.config.js` 中 `devServer.port` 确实是 8083，但 package.json 里 npm scripts 中的 serve 命令，行内的 `--port` 选项 还是 8082，由于优先级的原因导致 项目运行在 8082 端口下。修改为 8083 后，运行结果便和“博文中的效果”一致了。

留下此 issue，除了问下作者：这里是不是修改之后没改回来？ 也在提醒/解惑后来人 👀

**Comment by AshesOfHistory** [comment]
感谢反馈，我将在代码中修复

**Comment by AshesOfHistory** [comment]
已修复
